web: 
  build: .
  command: sh -c 'npm install; npm start'
  ports: 
    - '3030:3030'
  volumes:
    - /home/facundo/Escritorio/api/receta/api:/api
  links:
    - 'db:redis'

db:
  image: redis
  ports:
    - "6379:6379"

